### ISSUE TITLE
Add support for BitShares paperwallet

### ISSUE THREAD

**Issue by sschiessl-bcp** [technologiespro/paper-wallet-generator#1]
Would be awesome to have that possibility as well.

**Comment by technologiespro** [comment]
Thank you. 
Added Bitshares today in the new version - welcome.

https://github.com/technologiespro/paper-wallet-generator/releases/tag/1.0.7

Available for download as desktop and in a light version from the dist folder.
Soon, versions are expected under other OS and mobile.
